# Generated by Django 5.1.7 on 2025-03-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_blog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="summary",
        ),
        migrations.AddField(
            model_name="blog",
            name="title",
            field=models.CharField(default="Title", max_length=255),
            preserve_default=False,
        ),
    ]
