# Generated by Django 5.1.7 on 2025-03-15 23:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_remove_blog_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="body",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="blog",
            name="pubdate",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="blog",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
