# Generated by Django 5.1.7 on 2025-03-20 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_blog_body_blog_pubdate_blog_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
