# Generated by Django 5.1.7 on 2025-03-17 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                ("pubdate", models.DateTimeField(default=django.utils.timezone.now)),
                ("body", models.TextField(default="")),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
