# Generated by Django 5.1.7 on 2025-03-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="pubdate",
        ),
        migrations.AddField(
            model_name="blog",
            name="pub_date",
            field=models.DateTimeField(default="2021-03-03"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="body",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
